## sesi 4

In [38]:
import numpy as np

In [39]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [40]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [41]:
np.array([[1,2,3,4], [5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [137]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [43]:
print(a[0])

[1 2 3 4]


In [44]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
a.ndim

2

In [46]:
a.shape

(3, 4)

In [47]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]], [[9,10], [11,12]]])

In [48]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [49]:
b.ndim

3

In [50]:
b.shape

(3, 2, 2)

### array




##### np.array()
##### np.zeros()
##### np.ones()
##### np.empty()
##### np.arrange()

In [51]:
np.array([1,2,3])

array([1, 2, 3])

In [52]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [53]:
np.zeros(2)

array([0., 0.])

In [54]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [55]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
np.ones(2)

array([1., 1.])

In [58]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [59]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [60]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in

In [61]:
np.empty(2)

array([1., 1.])

In [62]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [63]:
np.empty((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [64]:
np.arange(5)

array([0, 1, 2, 3, 4])

### add, remove, sort

##### np.append()
##### np.delete()
##### np.sort()

In [65]:
arr = np.arange(8)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [67]:
np.append(arr, [1]) #tambah di akhir

array([0, 1, 2, 3, 4, 5, 6, 7, 1])

In [68]:
np.append(arr, [1,2])

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [69]:
arr = np.append(arr, [1,2])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [70]:
np.delete(arr, [1]) #yang kehapus index keberapanya

array([0, 2, 3, 4, 5, 6, 7, 1, 2])

In [71]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [72]:
np.sort(arr)

array([0, 1, 1, 2, 2, 3, 4, 5, 6, 7])

### ndim, size, shape

##### arr.ndim()
##### arr.size()
##### arr.shape()

In [73]:
print("dim: ", arr.ndim)
print("size: ", arr.size)
print("shape: ", arr.shape)

dim:  1
size:  10
shape:  (10,)


In [74]:
help(np.shape) #index awal - akhir

Help on _ArrayFunctionDispatcher in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    len : ``len(a)`` is equivalent to ``np.shape(a)[0]`` for N-D arrays with
          ``N>=1``.
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 3]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4), (5, 6)],
    ...              dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (3,)
    >>> a.shape
    (3,)



### reshape

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [76]:
arr.shape

(10,)

In [ ]:
arr.reshape(3,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [1, 2, 1, 2]])

In [ ]:
arr.reshape(4,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 1],
       [2, 1, 2]])

In [ ]:
arr.reshape(6,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2],
       [1, 2]])

In [ ]:
arr.reshape(6,2,1)

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]],

       [[1],
        [2]],

       [[1],
        [2]]])

In [79]:
arr3 = arr.reshape(5,2)

In [80]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

### convert 1D to 2D

#### np.newaxis


In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [82]:
arr[np.newaxis] #berguna untuk menambah dimensi diluar saja

array([[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]])

In [83]:
arr.shape

(10,)

In [87]:
arr4 = arr[np.newaxis, :]

In [85]:
arr4.ndim

2

In [86]:
arr4.shape 

(1, 10)

#### np.expand_dims

In [90]:
a 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
a.shape

(3, 4)

In [89]:
np.expand_dims(a, axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [92]:
np.expand_dims(a, axis = 0).shape

(1, 3, 4)

In [93]:
np.expand_dims(a, axis = 1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [95]:
np.expand_dims(a, axis = 1).shape

(3, 1, 4)

In [96]:
a[np.newaxis, :] #sama seperti expand_dims dengan axis = 0

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

### indexing and slicing

In [97]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [99]:
arr[4:] #index ke4

array([4, 5, 6, 7, 1, 2])

In [100]:
arr>2

array([False, False, False,  True,  True,  True,  True,  True, False,
       False])

In [102]:
arr[arr>2] #hanya yang bernilai True

array([3, 4, 5, 6, 7])

In [138]:
a 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
a < 8

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [105]:
a[a<8]

array([1, 2, 3, 4, 5, 6, 7])

In [107]:
#contoh cari yang genap
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [109]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [112]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [110]:
a % 3 == 0

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [113]:
(a % 2 == 0) & (a % 3 == 0)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

### creating from existing data

#### np.vstack()
#### np.hstack()

In [117]:
arr1 = arr[3:8]

In [118]:
arr1

array([3, 4, 5, 6, 7])

In [126]:
a_1 = np.array(([1,1], [2,2]))
print(a_1.shape)
a_1

(2, 2)


array([[1, 1],
       [2, 2]])

In [127]:
a_2 = np.array(([3,3], [4,4]))
print(a_2.shape)
a_2

(2, 2)


array([[3, 3],
       [4, 4]])

In [128]:
np.vstack(([a_1, a_2])) #menggabungkan array secara vertikal, jumlah kolom harus sama

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [125]:
np.hstack(([a_1, a_2])) #menggabungkan array secara horizontal, jumlah baris harus sama

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

#### np.hsplit()
#### np.vsplit()

In [131]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12], 
    [13,14,15,16,17,18,19,20,21,22,23,24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [140]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [141]:
np.hsplit(a,4)

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [142]:
np.vsplit(a,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [144]:
np.vstack(np.vsplit(a,3)) #balik jadi a utuh lagi

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### .view()
#### .copy()

In [145]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [146]:
b =a

In [151]:
print(id(a))
print(id(b))
print(id(a) == id(b))

2754602708848
2754602708848
True


In [152]:
b = a.view() #keguaannya untuk tampilan baru dengan memori yang berbeda

In [153]:
print(id(a))
print(id(b))
print(id(a) == id(b))

2754602708848
2754606201712
False


In [154]:
c = a.copy()

In [155]:
print(id(a))
print(id(c))
print(id(a) == id(c))

2754602708848
2754606202288
False


perbedaan .view() dan .copy() adalah .copy() membuat salinan fisik yang independen dari data, sedangkan .view() hanya memberikan tampilan yang melihat data yang sudah ada

### basic array operation

#### +
#### -
#### /
#### *

In [157]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [159]:
arr + 1 #berlaku ke seluruh index

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3])

In [160]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35,  5, 10])

In [162]:
data = np.array([1,2])
data

array([1, 2])

In [165]:
ones = np.ones(2)
ones

array([1., 1.])

In [166]:
data + ones

array([2., 3.])

In [167]:
data * ones

array([1., 2.])

### broadcasting

In [168]:
data * 2

array([2, 4])

In [169]:
data + 2

array([3, 4])

### array operation

#### data.max()
#### data.min()
#### data.sum()
#### data.mean()
#### data.median()

In [172]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [174]:
print(arr.max())
print(arr.min())
print(arr.sum())

7
0
31


In [176]:
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))

7
0
31


### matrices

In [177]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [178]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [182]:
np.random.random((3,2))

array([[0.5084651 , 0.04112493],
       [0.6966367 , 0.52899327],
       [0.18589289, 0.145825  ]])

### matrix arithmetic

In [188]:
data = np.arange(1,5).reshape(2,2)
ones = np.ones((2,2))
ones_row = np.ones((2))

print(data)
print(ones)
print(ones_row)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[1. 1.]


In [187]:
print(data+ones)

[[2. 3.]
 [4. 5.]]


In [189]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### dot product

In [191]:
a_1 = np.array(([1,2,3], [4,5,6]))
print(a_1)
print(a_1.shape)


a_2 = np.array(([7,8], [9,10], [11,12]))
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [192]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### matrix indexing

In [193]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [194]:
a[0]

array([1, 2, 3, 4])

In [195]:
a[1]

array([5, 6, 7, 8])

In [196]:
a[2]

array([ 9, 10, 11, 12])

In [197]:
a[0][0]

1

In [198]:
a[0][1]

2

In [199]:
a[2][-1]

12

In [201]:
data = np.array([[1,2], [3,4], [5,6]])
print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### transposing

In [202]:
data 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [204]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [205]:
np.transpose(data)

array([[1, 3, 5],
       [2, 4, 6]])

In [206]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [207]:
data.shape

(3, 2)

In [208]:
data.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [212]:
np.linspace(1,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [213]:
np.linspace(0,50, num=100)

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84